In [1]:
import matplotlib.pyplot as plt 
import numpy as np
import seaborn as sns
import pandas as pd

In [2]:
df=pd.read_csv('final_df.csv')
df

,species,sepal_length_Bin,sepal_width_Bin,petal_length_Bin,petal_width_Bin,id,petal_length_width_log,sepal_length_width_log
0,setosa,big,average,small,small,0,0.470004,2.151762
1,setosa,big,average,small,small,1,0.470004,2.066863
2,setosa,big,average,small,small,2,0.405465,2.066863
3,setosa,big,average,small,small,3,0.530628,2.041220
4,setosa,big,average,small,small,4,0.470004,2.151762
...,...,...,...,...,...,...,...,...
145,virginica,very big,average,big,average,145,2.014903,2.272126
146,virginica,very big,average,big,small,146,1.931521,2.174752
147,virginica,very big,average,big,small,147,1.974081,2.251292
148,virginica,very big,average,big,average,148,2.041220,2.261763
149,virginica,big,average,big,small,149,1.931521,2.186051

In [5]:
X=df.drop(columns=['species','sepal_length_width_log'],axis=1)
Y=df['species']

In [6]:
X=pd.get_dummies(X)
X

,id,petal_length_width_log,sepal_length_Bin_big,sepal_length_Bin_very big,sepal_width_Bin_average,sepal_width_Bin_big,sepal_width_Bin_small,petal_length_Bin_average,petal_length_Bin_big,petal_length_Bin_small,petal_length_Bin_very big,petal_width_Bin_average,petal_width_Bin_small
0,0,0.470004,1,0,1,0,0,0,0,1,0,0,1
1,1,0.470004,1,0,1,0,0,0,0,1,0,0,1
2,2,0.405465,1,0,1,0,0,0,0,1,0,0,1
3,3,0.530628,1,0,1,0,0,0,0,1,0,0,1
4,4,0.470004,1,0,1,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,145,2.014903,0,1,1,0,0,0,1,0,0,1,0
146,146,1.931521,0,1,1,0,0,0,1,0,0,0,1
147,147,1.974081,0,1,1,0,0,0,1,0,0,0,1
148,148,2.041220,0,1,1,0,0,0,1,0,0,1,0
149,149,1.931521,1,0,1,0,0,0,1,0,0,0,1

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y)
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(X_train,Y_train)

(112, 13) (38, 13) (112,) (38,)

/home/yashprime1/.local/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [8]:
model.score(X_train,Y_train)

0.9910714285714286

In [9]:
model.score(X_test,Y_test)

1.0

In [10]:
Y_pred=model.predict(X_test)

In [11]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test,Y_pred)
def print_score(actual,prediction):
    cm=confusion_matrix(actual,prediction)
    tp=cm[1,1]
    tn=cm[0,0]
    fp=cm[0,1]
    fn=cm[1,0]
    print("Overall Accuracy : ",(tp+tn)/(tp+tn+fp+fn))
    print("Precision : ",(tp)/(tp+fp))
    print("Recall or TPR or Sensitivity: ",(tp)/(tp+fn))
    print("Specificity or TNR: ",(tn)/(tn+fp))

In [12]:
print_score(Y_test,Y_pred)

Overall Accuracy :  1.0
Precision :  1.0
Recall or TPR or Sensitivity:  1.0
Specificity or TNR:  1.0